/**:
  ros__parameters:
    wheel_radius: 0.1
    wheel_thickness: 0.05
    caster_radius: 0.02
    base_length: 0.25
    base_width: 0.225
    base_height: 0.055

    base_mass: 2.5
    wheel_mass: 0.35
    caster_mass: 0.15