<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddrive">

    <!-- include the gazebo xacro file -->
    <xacro:include filename="$(find diff_drive)/ddrive.gazebo.xacro" />
    <!-- loading in parameter file -->
    <xacro:property name="yaml_file" value="$(find diff_drive)/config/ddrive.yaml" />
    <xacro:property name="props" value="${xacro.load_yaml(yaml_file)['/**']['ros__parameters']}" />
    
    <!-- dimension parameters of robot -->
    <xacro:property name="wheel_radius" value="${props['wheel_radius']}"/>
    <!-- note: the caster is a sphere -->
    <xacro:property name="caster_radius" value="${props['caster_radius']}"/>
    <xacro:property name="base_length" value="${props['base_length']}"/>
    <xacro:property name="base_width" value="${props['base_width']}"/>
    <xacro:property name="base_height" value="${props['base_height']}"/>
    <!-- mass parameters of robot -->
    <xacro:property name="base_mass" value="${props['base_mass']}"/>
    <xacro:property name="wheel_mass" value="${props['wheel_mass']}"/>
    <xacro:property name="caster_mass" value="${props['caster_mass']}"/>
    <xacro:property name="wheel_thickness" value="${props['wheel_thickness']}"/>
    <!-- constant dimensions -->
    <!-- <xacro:property name="wheel_thickness" value="0.2"/> -->

    <!-- the odom link and joint -->
    <!-- displacement in z chosen to mirror that of the robot being spawned in gazebo -->
    <!-- <link name="odom">
    </link> -->

    <!-- <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="odom"/>
        <child link="base_link"/>
    </joint>
     -->
    <!-- the robot base_link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </collision>
        <inertial>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <mass value="${base_mass}"/>
            <inertia ixx="${(1/12)*(base_mass)*(base_width**2+base_height**2)}" ixy="0.0" ixz="0.0" iyy="${(1/12)*(base_mass)*(base_height**2+base_length**2)}" iyz="0.0" izz="${(1/12)*(base_mass)*(base_width**2+base_length**2)}"/>    
        </inertial>
    </link>

    <!-- the l_wheel (left wheel) joint and link -->
    <joint name="l_wheel_joint" type="continuous">
        <origin xyz="${base_length/4} ${base_width/2} ${base_height/2}" rpy="-1.57079632679 0 0"/>
        <parent link="base_link"/>
        <child link="l_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" velocity="1000.0"/>
    </joint>

    <link name="l_wheel_link"   >
        <visual>
            <origin xyz="0 0 ${wheel_thickness/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="orange">
                <color rgba="1 0.5 0.1 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${wheel_thickness/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="orange">
                <color rgba="1 0.5 0.1 1"/>
            </material>
            <!-- <surface>
                <friction>
                    <ode>
                        <mu>1.0</mu>
                        <mu2>0.25</mu2>
                    </ode>
                </friction>
            </surface> -->
        </collision>
        <inertial>
            <origin xyz="0 0 ${wheel_thickness/2}" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${(1/12)*(wheel_mass)*(3*wheel_radius**2+wheel_thickness**2)}" ixy="0.0" ixz="0.0" iyy="${(1/12)*(wheel_mass)*(3*wheel_radius**2+wheel_thickness**2)}" iyz="0.0" izz="${(1/2)*(wheel_mass)*(wheel_radius**2)}"/>
        </inertial>
    </link>

    <!-- the r_wheel (right wheel) joint and link -->
    <joint name="r_wheel_joint" type="continuous">
        <origin xyz="${base_length/4} -${base_width/2} ${base_height/2}" rpy="-1.57079632679 0 0"/>
        <parent link="base_link"/>
        <child link="r_wheel_link"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" velocity="1000.0"/>
    </joint>

    <link name="r_wheel_link">
        <visual>
            <origin xyz="0 0 -${wheel_thickness/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="red">
                <color rgba="1 0.2 0.2 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 -${wheel_thickness/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="red">
                <color rgba="1 0.2 0.2 1"/>
            </material>
            <!-- <surface>
                <friction>
                    <ode>
                        <mu>1.0</mu>
                        <mu2>0.25</mu2>
                    </ode>
                </friction>
            </surface> -->
        </collision>
        <inertial>
            <origin xyz="0 0 -${wheel_thickness/2}" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${(1/12)*(wheel_mass)*(3*wheel_radius**2+wheel_thickness**2)}" ixy="0.0" ixz="0.0" iyy="${(1/12)*(wheel_mass)*(3*wheel_radius**2+wheel_thickness**2)}" iyz="0.0" izz="${(1/2)*(wheel_mass)*(wheel_radius**2)}"/>
        </inertial>
    </link>

    <!-- the t_caster (top caster wheel) joint and link -->
    <joint name="t_caster_joint" type="fixed">
        <origin xyz="-${2*base_length/5} 0 ${base_height}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="t_caster_link"/>
    </joint>

    <link name="t_caster_link">
        <visual>
            <origin xyz="0 0 ${caster_radius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name = "blue">
                <color rgba="0.2 0.2 1 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${caster_radius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name = "blue">
                <color rgba="0.2 0.2 1 1"/>
            </material>
            <surface>
                <friction>
                    <ode>
                        <mu1>0.0</mu1>
                        <mu2>0.0</mu2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <inertial>
            <origin xyz="0 0 ${caster_radius}" rpy="0 0 0"/>
            <mass value="${caster_mass}"/>
            <inertia ixx="${(2/5)*(caster_mass)*(caster_radius**2)}" ixy="0.0" ixz="0.0" iyy="${(2/5)*(caster_mass)*(caster_radius**2)}" iyz="0.0" izz="${(2/5)*(caster_mass)*(caster_radius**2)}"/>
        </inertial>
    </link>

    <!-- the b_caster (bottom caster wheel) joint and link -->
    <joint name="b_caster_joint" type="fixed">
        <origin xyz="-${2*base_length/5} 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="b_caster_link"/>
    </joint>

    <link name="b_caster_link">
        <visual>
            <origin xyz="0 0 -${caster_radius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="yellow">
                <color rgba="1 1 0.2 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 -${caster_radius}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="yellow">
                <color rgba="1 1 0.2 1"/>
            </material>
            <surface>
                <friction>
                    <ode>
                        <mu1>0.0</mu1>
                        <mu2>0.0</mu2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <inertial>
            <origin xyz="0 0 -${caster_radius}" rpy="0 0 0"/>
            <mass value="${caster_mass}"/>
            <inertia ixx="${(2/5)*(caster_mass)*(caster_radius**2)}" ixy="0.0" ixz="0.0" iyy="${(2/5)*(caster_mass)*(caster_radius**2)}" iyz="0.0" izz="${(2/5)*(caster_mass)*(caster_radius**2)}"/>
        </inertial>
    </link>

</robot>